### ISSUE TITLE
Firefox won't work again until restarted on server restart

### ISSUE THREAD

**Issue by keyle** [Flotype/now#13] opened 2011-03-17 04:04 UTC
Firefox mac 3.5.3.

steps to reproduce
- use the example
- works perfect 
- restart the server
- refresh chrome, all good, app restarts
- refresh firefox, nothing works anymore, dead. 

the server still receives the messages and broadcasts them but it doesn't get passed to firefox. Firefox needs to be entirely quit and started again.

I realize this is probably a problem with firefox and sockets. it's pretty flimsy though.

**Comment by ericz** [comment] 2011-03-17 04:25
Nice find! I'll look into this tonight.

Thanks

**Comment by ericz** [comment] 2011-03-18 02:39
Well we can definitely reproduce the bug. Still debugging...

**Comment by keyle** [comment] 2011-03-20 05:28
any updates? I get serious problems with Firefox.. 

20 Mar 15:27:21 - Initializing client with transport "xhr-multipart"
20 Mar 15:27:21 - Client 07681131735444069 connected

then nothing, on now.ready I'm calling things - no response!

**Comment by ssebro** [comment] 2011-03-20 23:36
I can add more clarity to this bug: it seems that socket.io isn't working well with different clients using different transports. If your first attendant logs into the room with Safari 5.0.4 on a mac, safari-safari chats work fine. If your second attendant logs in with firefox (3.6.13), safari-safari chats continnue to work, but firefox users can neither send nor receive messages. Similarly, if you log in with chrome (10.0.648.151), chrome users can send messages, but don't get to receive messages (from themselves or from anyone else). Each client mentioned uses a different transport - I'm not sure if that's a part of the problem.

**Comment by keyle** [comment] 2011-03-25 14:20
any news on this?

**Comment by ericz** [comment] 2011-03-30 19:59
hey Keyle and ssebro

I have been able to replicate <Edit> some of  </Edit> these bugs. The key seems to be when xhr-polling and xhr-multipart are involved, weird things happened with regards to connect and disconnect events.  

It seems like the issues are with the Socket.IO library we depend on. I know a major version release for Socket.IO is coming so hopefully these issues are fixed.

Also xhr-multipart/xhr-polling in Firefox are fallbacks to the prefered Flashsocket method (if the user has Flash installed).

Keyle, I'm guessing this has something to do with the cookie which stores chosen transport method. The weird part is the clientId in socket.io doesn't change.

I'm going to wait a bit more for v0.7 to come out to see if this issue is fixed. I can't replicated this consistently so I'm not sure the next steps to take.

**Comment by keyle** [comment] 2011-03-30 23:18
Ok thanks Eric.

**Comment by ssebro** [comment] 2011-03-31 01:52
Yeah, thanks a lot - I appreciate you following up.

**Comment by ericz** [comment] 2011-03-31 15:15
Hey guys,

3rdEden messaged me on Twitter and he was having trouble reproducing these bugs. Using the latest version of nowjs, socket.io, and respective browsers I haven't been able to reproduce them anymore either.

Additionally he mentioned v0.7 of socket.io probably won't include updates that are related to the problems we're seeing.

I'm going to test some more with different versions but I believe the issues may be fixed already in the latest versions of everything? I am not sure whether the original bug was in NowJS (may very well be) or socket.io or browsers, but I am unable to reproduce them anymore

**Comment by ssebro** [comment] 2011-04-03 06:31
I agree, I just fired it up on all three (ffox, safari, chrome) and did chat fine... Seems fixed to me...

**Comment by ssebro** [comment] 2011-04-03 06:32
Maybe we can have Keyle test on his machine and close this as unable to reproduce?

**Comment by ericz** [comment] 2011-04-05 16:48
Closing

**Closed as completed by ericz** 2011-04-05 16:48 UTC
