### ISSUE TITLE
command line client

### ISSUE THREAD

**Issue by hasenj** [Flotype/now#153] opened 2011-10-30 15:44 UTC
How do I setup the client if it's a command line program? i.e. not a browser.

**Comment by ericz** [comment] 2011-11-01 22:19
Hi hasenj,

Do you mean how to use node.js as a client for a nowjs server?

**Comment by hasenj** [comment] 2011-11-02 06:35
Hi ericz,

Yea, I'm thinking of it as a way to talk to the server without explicitly sending a request to a specific URL.

**Comment by ericz** [comment] 2011-11-02 13:04
Hey hasenj,

Unfortunately for NowJS there is no network-level protcol that would allow you to directly talk to the server without sending a specific URL. However it is possible to build a client specific to your environment that would allow you to talk to the server directly, most of the time.

Eric

**Comment by hasenj** [comment] 2011-11-02 13:11
Hm, either I'm confused or perhaps I didn't express my idea correctly.

Looking at the chat example, this line:

```
now.distributeMessage($("#text-input").val());
```

Calls a function on the server, no?

And likewise, the server can call a function on the client.

This is the kind of thing I meant.

Is there a technical limitation that makes this not possible outside the browser? e.g. it depends on websockets and there's no way to emulate that?

**Comment by ericz** [comment] 2011-11-02 13:16
hi hasenj,

Yes the issue is primarily that it requires either websockets or a compatible http fallback. Other than that there is nothing prohibiting a non-browser client from being created. For example, a node.js client can be created simply by using the node.js websocket module and removing references to the dom in the client lib.

**Comment by sharadmv** [comment] 2011-12-10 06:41
Hello,

You can now use NowJS from the node command line. See the example at: 

https://github.com/Flotype/now/tree/master/examples/nodeclient_example

Note that this is experimental and has inefficiencies.

**Comment by ericz** [comment] 2012-01-16 20:02
Closing. Feel free to reopen if there are additional issues.

**Closed as completed by ericz** 2012-01-16 20:02 UTC
