### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by ubershmekel** [Flotype/now#21] opened 2011-03-21 23:33 UTC
I'm using node 0.4.3 (without https) and nowjs 0.3 on a virtualbox ubuntu. I get this error message when I try to send a message on the example chat:

```
22 Mar 01:27:02 - xhr-multipart message handler error - TypeError: Object #<Object> has no method 'receiveMessage'
at Object.<anonymous> (/home/john/local/node/lib/node/.npm/now/0.3.0/package/examples/helloworld_server.js:22:65)
at Object.remoteCall (/home/john/local/node/lib/node/.npm/now/0.3.0/package/lib/nowServerLib.js:187:15)
at [object Object].<anonymous> (/home/john/local/node/lib/node/.npm/now/0.3.0/package/lib/nowServerLib.js:127:48)
at [object Object].emit (events.js:64:17)
at [object Object]._onMessage (/home/john/local/node/lib/node/.npm/socket.io/0.6.16/package/lib/socket.io/client.js:58:10)
at IncomingMessage.<anonymous> (/home/john/local/node/lib/node/.npm/socket.io/0.6.16/package/lib/socket.io/transports/xhr-multipart.js:48:16)
at IncomingMessage.emit (events.js:61:17)
at HTTPParser.onMessageComplete (http.js:132:23)
at Socket.ondata (http.js:1001:22)
at Socket._onReadable (net.js:675:27)
```

**Comment by ericz** [comment] 2011-03-22 16:41
Very interesting. Do you get this issue with other browsers?

**Comment by ubershmekel** [comment] 2011-03-22 20:18
The error was with firefox 3.6.10 and after testing I can say the nowjs
example does work with chrome.

After some idle time this is printed out at the server:

(node) warning: possible EventEmitter memory leak detected. 11 listeners
added. Use emitter.setMaxListeners() to increase limit.
Trace:
    at Socket.<anonymous> (events.js:123:17)
    at [object Object].<anonymous> (/home/john/local/node/lib/node/.npm/
socket.io/0.6.16/package/lib/socket.io/client.js:83:20)
    at [object Object]._onConnect (/home/john/local/node/lib/node/.npm/
socket.io/0.6.16/package/lib/socket.io/transports/xhr-polling.js:23:35)
    at [object Object].check (/home/john/local/node/lib/node/.npm/
socket.io/0.6.16/package/lib/socket.io/listener.js:77:12)
    at Server.<anonymous> (/home/john/local/node/lib/node/.npm/
socket.io/0.6.16/package/lib/socket.io/listener.js:33:14)
    at Server.emit (events.js:67:17)
    at HTTPParser.onIncoming (http.js:1102:12)
    at HTTPParser.onHeadersComplete (http.js:108:31)
    at Socket.ondata (http.js:1001:22)
    at Socket._onReadable (net.js:675:27)
(node) warning: possible EventEmitter memory leak detected. 11 listeners
added. Use emitter.setMaxListeners() to increase limit.
Trace:
    at Socket.<anonymous> (events.js:123:17)
    at [object Object].<anonymous> (/home/john/local/node/lib/node/.npm/
socket.io/0.6.16/package/lib/socket.io/client.js:70:19)
    at [object Object]._onConnect (/home/john/local/node/lib/node/.npm/
socket.io/0.6.16/package/lib/socket.io/transports/xhr-polling.js:23:35)
    at [object Object].check (/home/john/local/node/lib/node/.npm/
socket.io/0.6.16/package/lib/socket.io/listener.js:77:12)
    at Server.<anonymous> (/home/john/local/node/lib/node/.npm/
socket.io/0.6.16/package/lib/socket.io/listener.js:33:14)
    at Server.emit (events.js:67:17)
    at HTTPParser.onIncoming (http.js:1102:12)
    at HTTPParser.onHeadersComplete (http.js:108:31)
    at Socket.ondata (http.js:1001:22)
    at Socket._onReadable (net.js:675:27)

So this is probably a whole other issue.

**Comment by ericz** [comment] 2011-03-26 17:14
Hey ubershmekel,

Can you try using the latest version of nowjs in Github/npm. We rolled out several crucial bug fixes that may or may not fix this issue. If you still have it with the latest npm version (v0.3.1) then I'll have a better idea of what is going on.

Thanks,
Eric

**Comment by swalkergibson** [comment] 2011-03-26 19:10
Hi Eric,

I was having the same issue as ubershmekel. I just npm'd the latest code and the original error has now gone away, but a new one has just presented itself. It is now possible to create one connection to the nowjs server, but not a second. Additionally, the first connection reports the following:

26 Mar 12:01:33 - socket.io ready - accepting connections
26 Mar 12:01:46 - Initializing client with transport "xhr-multipart"
26 Mar 12:01:46 - Client 3002093662507832 connected
Joined: Shane
26 Mar 12:01:48 - Initializing client with transport "flashsocket"
26 Mar 12:01:48 - Client 20963806682266295 connected
Joined: Shane

This results in each message sent to the server from the first client being duplicated in the messages container. I hope that helps!

Shane

**Comment by ericz** [comment] 2011-03-26 19:12
Hey Shane,

What browser are you using?

Thanks,
Eric

On Sat, Mar 26, 2011 at 12:10 PM, swalkergibson
reply@reply.github.com
wrote:

> Hi Eric,
> 
> I was having the same issue as ubershmekel. I just npm'd the latest code and the original error has now gone away, but a new one has just presented itself. It is now possible to create one connection to the nowjs server, but not a second. Additionally, the first connection reports the following:
> 
> 26 Mar 12:01:33 - socket.io ready - accepting connections
> 26 Mar 12:01:46 - Initializing client with transport "xhr-multipart"
> 26 Mar 12:01:46 - Client 3002093662507832 connected
> Joined: Shane
> 26 Mar 12:01:48 - Initializing client with transport "flashsocket"
> 26 Mar 12:01:48 - Client 20963806682266295 connected
> Joined: Shane
> 
> This results in each message sent to the server from the first client being duplicated in the messages container. I hope that helps!
> 
> Shane
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Flotype/now/issues/21#comment_920929

## 

510-691-3951
EECS Student at UC Berkeley
http://ericzhang.com

**Comment by swalkergibson** [comment] 2011-03-26 19:13
Firefox 3.6.3 on Ubuntu 9.04

**Comment by ericz** [comment] 2011-04-04 06:24
hi swalkergibson,

We have been able to reproduce the double connection bug and we're investigating thoroughly now. The cause is the name prompt window in the hello world example, it causes weird behavior because it blocks the javascript thread. This is a completely solvable bug and we'll be working on it.

Thanks,
Eric

**Comment by ericz** [comment] 2011-04-04 17:24
Hey guys, the double connection issue has been reported here: https://github.com/LearnBoost/Socket.IO/issues/128

Closing now.

**Closed as completed by ericz** 2011-04-04 17:24 UTC
